"""Encode an approved RGBA avatar as a flash-resident LVGL bitmap, no PNG decoder.

Image generation/editing is performed separately. This build step only scales and
encodes the supplied asset. Requires Pillow; run with the project's path as cwd.
"""
import argparse
from pathlib import Path
from PIL import Image


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--output", type=Path, required=True)
    parser.add_argument("--side", type=int, choices=(64, 128), default=64)
    parser.add_argument("--symbol", default="kKanshanBwImage")
    parser.add_argument("--preview", type=Path)
    args = parser.parse_args()
    image = Image.open(args.source).convert("RGBA")
    if image.getchannel("A").getextrema()[0] == 255:
        raise ValueError("Expected an actually transparent source image")
    if not args.symbol.isidentifier():
        parser.error("symbol must be a C++ identifier")
    side = args.side
    image = image.resize((side, side), Image.Resampling.LANCZOS)
    raw = bytearray()
    for red, green, blue, alpha in image.getdata():
        raw.extend((blue, green, red, alpha))  # LVGL little-endian ARGB8888.
    lines = ["// Generated by custom_assets/build_bw_avatar.py; do not edit pixel data.",
             '#include "kanshan_bw_image.h"', "", "alignas(4) static const uint8_t kPixels[] = {"]
    for start in range(0, len(raw), 16):
        lines.append("    " + ", ".join(f"0x{value:02x}" for value in raw[start:start + 16]) + ",")
    lines.extend(["};", "", f"const lv_image_dsc_t {args.symbol} = {{",
                  "    .header = {.magic = LV_IMAGE_HEADER_MAGIC, .cf = LV_COLOR_FORMAT_ARGB8888,",
                  f"               .flags = 0, .w = {side}, .h = {side}, .stride = {side} * 4, .reserved_2 = 0}},",
                  "    .data_size = sizeof(kPixels),", "    .data = kPixels,", "};", ""])
    args.output.write_text("\n".join(lines), encoding="utf-8")
    image.save(args.preview or args.source.parent / f"liukanshan_bw_{side}.png")
    print(f"Generated {args.output}: {side}x{side} ARGB8888, {len(raw)} bytes in flash, no GIF canvas")


if __name__ == "__main__":
    main()
